In [1]:
# Data Encoding ---->> converting categarical columns into numeric

# Nominal / OHE[one hot encoding]
# Lable and ordinal encoding
# Target guided ordinal encoding


In [4]:
# Nominal / OHE  ---->> binary vector for each of the categaries
# example single, married, seprated
# single: [1,0,0]
# married: [0,1,0]
# seprated: [0,0,1]


In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [38]:
df = pd.DataFrame({"status": ["single", "married", "seprated", "single", "married"]})
df

status
0    single
1   married
2  seprated
3    single
4   married

In [39]:
encoder = OneHotEncoder()

In [40]:
encoder

OneHotEncoder()

In [41]:
encoded = encoder.fit_transform(df[["status"]]).toarray()

In [42]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [43]:
encoder.get_feature_names_out()

array(['status_married', 'status_seprated', 'status_single'], dtype=object)

In [44]:
encoder_df = pd.DataFrame(encoded,columns = encoder.get_feature_names_out())

In [45]:
encoder_df

status_married  status_seprated  status_single
0             0.0              0.0            1.0
1             1.0              0.0            0.0
2             0.0              1.0            0.0
3             0.0              0.0            1.0
4             1.0              0.0            0.0

In [46]:
encoder.transform([["single"]]).toarray()

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.]])

In [47]:
# pd.get_dumies()

In [48]:
pd.concat([df, encoder_df], axis= 1)

status  status_married  status_seprated  status_single
0    single             0.0              0.0            1.0
1   married             1.0              0.0            0.0
2  seprated             0.0              1.0            0.0
3    single             0.0              0.0            1.0
4   married             1.0              0.0            0.0

In [22]:
import seaborn as sns
sns.load_dataset("tips")

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [24]:
df = pd.DataFrame({"tips": ["total_bill", "tip", "sex", "day", "time", "size"]})
df

tips
0  total_bill
1         tip
2         sex
3         day
4        time
5        size

In [25]:
encoder = OneHotEncoder()

In [26]:
encoder

OneHotEncoder()

In [27]:
encoded = encoder.fit_transform(df[["tips"]]).toarray()

In [28]:
encoded

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [29]:
encoder.get_feature_names_out()

array(['tips_day', 'tips_sex', 'tips_size', 'tips_time', 'tips_tip',
       'tips_total_bill'], dtype=object)

In [30]:
encoder_df = pd.DataFrame(encoded,columns = encoder.get_feature_names_out())

In [31]:
encoder_df

tips_day  tips_sex  tips_size  tips_time  tips_tip  tips_total_bill
0       0.0       0.0        0.0        0.0       0.0              1.0
1       0.0       0.0        0.0        0.0       1.0              0.0
2       0.0       1.0        0.0        0.0       0.0              0.0
3       1.0       0.0        0.0        0.0       0.0              0.0
4       0.0       0.0        0.0        1.0       0.0              0.0
5       0.0       0.0        1.0        0.0       0.0              0.0

In [33]:
encoder.transform([["sex"]]).toarray()

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 1., 0., 0., 0., 0.]])

In [34]:
# Lable encoding --->> assign unique lable to the categories
# you can do using map or using library

In [36]:
df

status
0    single
1   married
2  seprated
3    single
4   married

In [52]:
from sklearn.preprocessing import LabelEncoder

In [55]:
lable_encoder = LabelEncoder ()

In [56]:
lable_encoder.fit_transform(df[["status"]])

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 2, 0])

In [57]:
lable_encoder.transform([["seprated"]])

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([1])

In [58]:
# Ordinal encoding

# Hign school : 1
# graduate : 2
# post graduate : 3
# phd : 4

In [59]:
from sklearn.preprocessing import OrdinalEncoder

In [60]:
df = pd.DataFrame({"qualification" : ["HS","GR","PG","PHD","HS","PHD"]})

In [61]:
df

qualification
0            HS
1            GR
2            PG
3           PHD
4            HS
5           PHD

In [62]:
encoder = OrdinalEncoder(categories=[["HS","GR","PG","PHD"]])

In [63]:
encoder

OrdinalEncoder(categories=[['HS', 'GR', 'PG', 'PHD']])

In [64]:
encoder.fit_transform(df[["qualification"]])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [3.]])

In [65]:
encoder.transform([["PG"]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[2.]])

In [66]:
# Target guided ordinal encoding

# relationship with target variable
# when a lot of unique categories
# replace category with mean and median of respective group

In [67]:
df = pd.DataFrame({'time':['lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner'],
             'total_bill': [120, 130, 90, 125, 150, 190, 160, 180, 189]})

In [78]:
df

time  total_bill  time_encoded
0      lunch         120    135.000000
1  breakfast         130    153.333333
2     dinner          90    156.333333
3      lunch         125    135.000000
4  breakfast         150    153.333333
5     dinner         190    156.333333
6      lunch         160    135.000000
7  breakfast         180    153.333333
8     dinner         189    156.333333

In [79]:
mean_price = df.groupby("time")["total_bill"].mean().to_dict()

In [76]:
df["time_encoded"] = df["time"].map(mean_price)

In [80]:
df["time_encoded"]

0    135.000000
1    153.333333
2    156.333333
3    135.000000
4    153.333333
5    156.333333
6    135.000000
7    153.333333
8    156.333333
Name: time_encoded, dtype: float64

In [81]:
df

time  total_bill  time_encoded
0      lunch         120    135.000000
1  breakfast         130    153.333333
2     dinner          90    156.333333
3      lunch         125    135.000000
4  breakfast         150    153.333333
5     dinner         190    156.333333
6      lunch         160    135.000000
7  breakfast         180    153.333333
8     dinner         189    156.333333